name:             Clementine
markdown:         kramdown
pygments:         false
exclude:          [
                    '.sass-cache',
                    'node_modules',
                    'scss',
                    'Gruntfile.js',
                    'package.json',
                    '*.sublime-project',
                    '*.sublime-workspace',
                    '*.bat',
                    '*.map',
                    '*.zip'
                  ]
